"""tenant_type on clinics

Revision ID: 800af70b2198
Revises: cfec55c85bb4
Create Date: 2026-05-19 09:50:56.045954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '800af70b2198'
down_revision: Union[str, None] = 'cfec55c85bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('tenant_type', sa.String(length=20), server_default='clinic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'tenant_type')
    # ### end Alembic commands ###
